package com.omt.omtest.network.dto

import com.omt.omtest.domain.*
import com.google.gson.annotations.SerializedName

data class Video (

    @SerializedName("metadata") val metadata : List<Metadata>,
    @SerializedName("prLevel") val prLevel : Int,
    @SerializedName("keywords") val keywordswords : String,
    @SerializedName("year") val year : Int,
    @SerializedName("seriesNumberOfEpisodes") val seriesNumberOfEpisodes : String,
    //@SerializedName("tvShowReference") val tvShowReference : TvShowReference,
    @SerializedName("episodeId") val episodeId : String,
    @SerializedName("type") val type : String,
    @SerializedName("assetExternalId") val assetExternalId : String,
    @SerializedName("contentProvider") val contentProvider : String,
    @SerializedName("reviews") val reviews : List<String>,
    @SerializedName("id") val id : Int,
    @SerializedName("rentalPeriodUnit") val rentalPeriodUnit : String,
    @SerializedName("isSecured") val isSecured : Boolean,
    @SerializedName("windowStart") val windowStart : Long,
    @SerializedName("adsInfo") val adsInfo : String,
    @SerializedName("seriesName") val seriesName : String,
    @SerializedName("prName") val prName : String,
    @SerializedName("rentalPeriod") val rentalPeriod : String,
    @SerializedName("name") val name : String,
    @SerializedName("broadcastTime") val broadcastTime : Int,
    @SerializedName("shortName") val shortName : String,
    @SerializedName("discountId") val discountId : String,
    @SerializedName("status") val status : Int,
    @SerializedName("advisories") val advisories : String,
    @SerializedName("template") val template : String,
    @SerializedName("attachments") val attachments : List<Attachments>,
    @SerializedName("chapters") val chapters : List<String>,
    @SerializedName("externalChannelId") val externalChannelId : String,
    @SerializedName("reviewerRating") val reviewerRating : String,
    @SerializedName("flags") val flags : Int,
    @SerializedName("description") val description : String,
    @SerializedName("seriesSeason") val seriesSeason : String,
    @SerializedName("allowedTerminalCategories") val allowedTerminalCategories : List<AllowedTerminalCategories>,
    @SerializedName("duration") val duration : Long,
    @SerializedName("genreEntityList") val genreEntityList : List<GenreEntityList>,
    @SerializedName("responseElementType") val responseElementType : String,
    @SerializedName("plannedPublishDate") val plannedPublishDate : String,
    @SerializedName("simultaneousViewsLimit") val simultaneousViewsLimit : String,
    @SerializedName("assetId") val assetId : Long,
    @SerializedName("genres") val genres : List<Int>,
    @SerializedName("pricingMatrixId") val pricingMatrixId : Int,
    @SerializedName("definition") val definition : String,
    @SerializedName("windowEnd") val windowEnd : Long,
    @SerializedName("encodings") val encodings : List<Encodings>,
    @SerializedName("externalId") val externalId : String,
    @SerializedName("removalDate") val removalDate : Long,
    @SerializedName("awards") val awards : List<String>,
    @SerializedName("extrafields") val extrafields : List<Extrafields>,
    @SerializedName("securityGroups") val securityGroups : List<String>,
    @SerializedName("contentProviderExternalId") val contentProviderExternalId : String,
    @SerializedName("categoryId") val categoryId : Int
)